#!/usr/bin/env bash

absolutePath(){
    [[ -d $1 ]] && { cd "$1"; echo "$(pwd -P)"; } ||
    ( cd "$(dirname "$1")" || exit 1; echo "$(pwd -P)/$(basename "$1")"; )
}

HERE=`absolutePath $0`
HERE=`dirname ${HERE}`
echo "${HERE}/grace compiler.js $*"
${HERE}/grace compiler.js $*
