#!/usr/bin/env bash

if [ "$1" ]
then
    case "$1" in
        --help)
            echo Environment preparation script for Mac OS X
            echo
            echo Usage: $0 "[command]"
            echo
            echo With no argument, launches a shell with the environment
            echo configured for C compilation.
            echo
            echo With arguments, sets up the environment and then executes
            echo the given command.
            exit 0
            ;;
    esac
fi

if [ -e /Developer ]
then
    DEVELOPER_PATH=/Developer
    SDKS_PATH=/Developer/SDKs
elif [ -e /Applications/Xcode.app ]
then
    DEVELOPER_PATH=/Applications/Xcode.app/Contents/Developer
    SDKS_PATH=$DEVELOPER_PATH/Platforms/MacOSX.platform/Developer/SDKs
fi

if ! [ "$DEVELOPER_PATH" ]
then
    echo "You need to install Xcode to compile."
    echo "It is available from the Mac App Store."
    exit 1
fi

export PATH=$DEVELOPER_PATH/usr/bin:"$PATH"

SDK=$(ls $SDKS_PATH|sort|tail -n 1)
if ! [ "$SDK" ]
then
    echo Could not find Mac OS X SDK. This script may need updating.
    exit 1
fi
echo "Found $SDK."
SDK_PATH=$SDKS_PATH/$SDK

export C_INCLUDE_PATH=$SDK_PATH/usr/include
export LIBRARY_PATH=$SDK_PATH/usr/lib

export IN_ENVIRON_SCRIPT=y
if [ "$1" ]
then
    exec $@
    exit $?
fi

echo Set environment variables PATH C_INCLUDE_PATH LIBRARY_PATH

echo Launching a shell with correctly-configured environment. Ctrl-D to exit.
echo ./configure, make, and the resulting minigrace executable should function
echo within this environment.
exec $SHELL
