#!/bin/bash

if [ ${BASH_VERSINFO[0]} -lt 4 ]
then
    echo "This script requires Bash 4.0 or newer." >&2
    exit 1
fi

declare -A authorCount
declare -A authorLength
declare -a names
maxlen=0
total=0
while read count name
do
    total=$((total + count))
    names=(${names:+"${names[@]}"} "$name")
    authorCount[$name]=$count
    len=$(wc -m <<<"$name")
    authorLength[$name]=$len
    if [[ $len -gt $maxlen ]]
    then
        maxlen=$len
    fi
done < <(git log --pretty=format:%aN ${1:+"$1"}|sort|uniq -c|sort -gr)

printf "Author %$((maxlen-8))s Commits  Proportion\\n" ""
for name in "${names[@]}"
do
    count=${authorCount[$name]}
    len=${authorLength[$name]}
    pc=$(bc <<<"scale=2;$count*100/$total")
    printf "%s %$((maxlen-len))s %'6i    %# 7.2f%%\\n" "$name" "" "$count" "$pc"
done
printf "%$((maxlen))s %'6i    %# 7.2f%%\\n" "" "$total" "100"
