#!/usr/bin/env bash

buildDate=$(date +"%B, %d, %Y")
ideVersion=$(cd grace-web-editor; git log --oneline | wc -l)
lastCommit=$(cd grace-web-editor; git rev-parse --short HEAD)

#Apply Formatting (Remove all spaces from ideVersion)
ideVersion=${ideVersion//[[:blank:]]/}


sed -i -e "s/IDE--VERSION/${ideVersion}/g" grace-web-editor/index.html
sed -i -e "s/LAST--GIT--COMMIT/${lastCommit}/g" grace-web-editor/index.html
sed -i -e "s/LASTBUILD-DATE/${buildDate}/g" grace-web-editor/index.html

