#!/bin/bash

set -e
mkdir -p .git-generation-cache
ct=0
RV=$1
[ "$RV" ] || RV=HEAD
h=$(git rev-parse $RV)
if [ -e .git-generation-cache/$h ]
then
    cat .git-generation-cache/$h
    exit 0
fi
for par in $(git show --format=%P -s $h)
do
    if [ -e .git-generation-cache/$par ]
    then
        nct=$((1 + $(cat .git-generation-cache/$par)))
    else
        nct=$($0 $par)
    fi
    if [ $nct -ge $ct ]
    then
        ct=$((nct + 1))
    fi
done
echo $ct > .git-generation-cache/$h
echo $ct
