#!/bin/bash

set -e
if [ ${BASH_VERSINFO[0]} -ge 4 ]
then
    . "$(dirname $0)"/generations.dat
    KNOWN=y
fi
mkdir -p .git-generation-cache
ct=0
RV=$1
[ "$RV" ] || RV=HEAD

findgen() {
    local RV=$1
    h=$(git rev-parse $RV)
    if [ "cc2ded6be7e705924e6a331ed01d8c3240ceb688" = "$h" ]
    then
        echo 857
        return 0
    elif [ "7c9986bc77c7f13621e4616f44c4be4fed710326" = "$h" ]
    then
        echo 1340
        return 0
    elif [ "08f7d89889a7bc8afac98ab1d0a6d10033a1d24d" = "$h" ]
    then
        echo 1674
        return 0
    elif [ "88855bc35225a388b52f1574488df3486543f510" = "$h" ]
    then
        echo 1926
        return 0
    fi
    if [ "$KNOWN" ] && [ "${known[$h]}" ]
    then
        echo ${known[$h]}
        return 0
    fi
    if [ -e .git-generation-cache/$h ]
    then
        cat .git-generation-cache/$h
        return 0
    fi
    for par in $(git show --format=%P -s $h)
    do
        if [ -e .git-generation-cache/$par ]
        then
            nct=$(cat .git-generation-cache/$par)
        else
            nct=$($0 $par)
        fi
        if [ $nct -ge $ct ]
        then
            ct=$((nct + 1))
        fi
    done
    echo $ct > .git-generation-cache/$h
    echo $ct
}

findgen "$RV"
