#!/usr/bin/env bash
BACKGROUND=""
for i in $*; do
    if [[ $i =~ .*\.js$ ]] &&
       [ $i != "js/tabs.js" ]; then
        BACKGROUND=${BACKGROUND}"  window.importScripts(\"../$i\");\n"
        INDEX=${INDEX}"    <script src=\"$i\" type=\"text/javascript\"></script>\n"
    fi
done
echo -e "${BACKGROUND}" > tools/jsltemp-file
sed -e '\#// JAVASCRIPT_SRC_FILES#r tools/jsltemp-file' grace-web-editor/scripts/background.in.js > grace-web-editor/scripts/background.js
echo -e "${INDEX}" > tools/jsltemp-file
sed -e '/JAVASCRIPT_SRC_FILES/r tools/jsltemp-file' grace-web-editor/index.in.html > grace-web-editor/index.html
rm -f tools/jsltemp-file
