#! /bin/sh -f
# a hack to get around the non-composable nature of dialects.
# Takes the name of a file and dumps an 'st' version of it to stdout.

N=`grep -n ^import "$1" | tail -n 1 | cut -f1 -d:`
L1='import "modules/staticTypes" as st'
L2='method checker(ast) { st.checker(ast) }'
sed  -e ${N}a"\\
$L1" -e ${N}a"\\
$L2" $1

