#!/bin/bash
# Use a tarball to provide known-good for bootstrapping

die() {
    echo "$@" >&2
    exit 1
}

TARBALL=$1

if ! [ "$TARBALL" ]
then
    echo "Usage: $0 <tarball>"
    echo "Compiles <tarball> and installs it as known-good bootstrap version."
    echo
    echo "Download the tarball of a past bootstrap version and pass it to"
    echo "this script as <tarball> to install it for bootstrapping. Afterwards"
    echo "\`make\` will build the latest version from the source repository."
    echo
    cd "$(git rev-parse --show-toplevel)"
    rev=$(awk -F= '/STABLE=/ { print $2 }' Makefile)
    gen=$(tools/git-calculate-generation "$rev")
    ver=$(git show --format=%B $rev:util.grace | sed -n 's/var versionNumber := "\([^"]*\)"/\1/p')
    if ! [ "$ver" ]
    then
        echo "The newest bootstrap tarball could not be calculated on your"
        echo "system, but a working tarball should be available from:"
        echo "   http://ecs.vuw.ac.nz/~mwh/minigrace/dist/minigrace-0.0.7.1033.tar.bz2"
        exit 0
    fi
    echo "The tarball for the newest bootstrapping version should be called:"
    echo "   minigrace-$ver.$gen.tar.bz2"
    echo "and should be available from:"
    echo "   http://ecs.vuw.ac.nz/~mwh/minigrace/dist/minigrace-$ver.$gen.tar.bz2"
    exit 0
fi

tar xjvf "$TARBALL" || die "Failed to extract tarball"
dir=$(sed 's/.tar.bz2//' < <(basename "$TARBALL"))
pushd "$dir"
./configure || die "Failed to configure tarball"
sed -i "" 's/-std=c99//' Makefile
make || die "Failed to build"
hash=$(./minigrace --version | awk '/git revision/ { print $3 }')
kgdir=../known-good/$(uname -s)-$(uname -m)/$hash
mkdir -p "$kgdir"
for f in gracelib.h gracelib.o minigrace unicode.gso unicode.gcn
do
    [ -e "$f" ] && cp $f "$kgdir/$f"
done
popd
rm -rf "$dir"

echo Installed tarball $TARBALL into $kgdir. You can now run make.
