#!/bin/bash

set -e
COMMIT=$1
ARCH=$2
FORM=$3

if which gmake >/dev/null 2>&1
then
    MAKE=gmake
else
    MAKE=make
fi

cat >EXCLUDE <<EOT
pax_global_header
known-good
tests
EOT

( cd $(git rev-parse --show-toplevel) && git archive --prefix=tmp-$$/ $COMMIT ) | tar xf - -X EXCLUDE
cd tmp-$$
ln -s .. known-good
GEN=$( ( cd $(git rev-parse --show-toplevel) && tools/git-calculate-generation "$COMMIT" ) )
echo "method gitrevision() { \"$COMMIT\" }" > buildinfo.gc
echo "method gitgeneration() { \"$GEN\" }" >> buildinfo.gc
cp buildinfo.gc buildinfo.grace
$MAKE l2/minigrace
cd ..

if [ "$FORM" = "hyphenated" ]
then
    mkdir -p "$ARCH"
    mv tmp-$$/l2/minigrace $ARCH/minigrace-$COMMIT
    cp tmp-$$/l2/gracelib.o $ARCH/gracelib-$COMMIT.o
    cp tmp-$$/l2/gracelib.h $ARCH/gracelib-$COMMIT.h
else
    mkdir -p "$ARCH/$COMMIT"
    mv tmp-$$/l2/minigrace $ARCH/$COMMIT
    cp tmp-$$/l2/gracelib.o $ARCH/$COMMIT/gracelib.o
    cp tmp-$$/l2/gracelib.h $ARCH/$COMMIT/gracelib.h
    [ -e tmp-$$/l2/gracelib.a ] && cp tmp-$$/l2/gracelib.a $ARCH/$COMMIT/gracelib.a
    cp tmp-$$/l2/unicode.gso $ARCH/$COMMIT
fi
for x in tmp-$$/l2/*.c
do
   nm=$(basename "$x")
   nm=$(cut -d. -f1 <<<"$nm")
   mv $x independent/$nm-$COMMIT.c
done

rm -rf tmp-$$ EXCLUDE
